//Check if userName Exsists
POST http://localhost:4000/Accounts/userCheck
Content-Type: application/json

{
  "userName": "admsin"
}
###

//Check Token
GET http://localhost:4000/Accounts/loggedin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImFkbWluIiwiaWF0IjoxNjcxMDUyNjMzLCJleHAiOjE2NzEwNTI5MzN9.GfAUyzZogo1BK0axjR4-EXg2r_HmAO2VW_era-AtwKo


###

//Create 
POST http://localhost:4000/Accounts/createAccount/
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Last Test",
  "dob": "Jan 29 2945",
  "email": "aetaet@email.ca",
  "address": "req.body.address",
  "city": "req.body.city",
  "country": "req.body.country",
  "userName": "req.body.userName",
  "password": "hashedPass" 
}

###

//Login Request 
POST http://localhost:4000/Accounts/login/
Content-Type: application/json

{
  "userName": "admin",
  "password": "test1234"
}

###

//Check Session
GET http://localhost:4000/Accounts/auth/

###

//Refresh Token 
POST http://localhost:4000/Accounts/token/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InRlc3QyIiwiaWF0IjoxNjcwOTY0MDAyfQ.-CvSi3Ax3MGMD9_7tx0JFbuLkcizKQqROQkoEAQxocQ"
}

###

//Delete Token 
DELETE http://localhost:4000/Accounts/logout/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6InRlc3QyIiwiaWF0IjoxNjcwOTY0MDAyfQ.-CvSi3Ax3MGMD9_7tx0JFbuLkcizKQqROQkoEAQxocQ"
}

###

//Get User Image
GET http://localhost:4000/Accounts/getUserImage/640ffda8aecbb534454886d6