//Get All
GET http://localhost:4000/Users/

###
//Get One By Id
GET http://localhost:4000/Users/63923b852d9b7817eea27c93

###
//Create
Post http://localhost:4000/Users/
Content-Type: application/json

{ 
  "lastName": "aTest", 
  "firstName": "User", 
  "DoB": "Nov 26 1972", 
  "address1": "4990 River St", 
  "address2": "N/A", 
  "city": "Camlachie", 
  "postalCode": "N0N 1E0", 
  "country": "Canada", 
  "phone": "549-876-4689", 
  "email": "jbob@email.com", 
  "notes": "Middle name Todd"
  }

###
//Replace
PUT http://localhost:4000/Users/63923b852d9b7817eea27c93
Content-Type: application/json

{ 
  "lastName": "Update", 
  "firstName": "Test", 
  "DoB": "Nov 26 1972", 
  "address1": "4990 River St", 
  "address2": "N/A", 
  "city": "Camlachie", 
  "postalCode": "N0N 1E0", 
  "country": "Canada", 
  "phone": "549-876-4689", 
  "email": "jbob@email.com", 
  "notes": "Middle name Todd"
  }

###
//Delete
DELETE http://localhost:4000/Users/63923b852d9b7817eea27c93